// lib/gpt.js
import OpenAI from "openai";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

export default function gpt(bot) {
  /* ================= GPT CHAT ================= */
  bot.command("gpt", async (ctx) => {
    const prompt = ctx.message.text.split(" ").slice(1).join(" ").trim();
    if (!prompt) return ctx.reply("❓ Usage: /gpt <question>");

    try {
      await ctx.replyWithChatAction("typing");

      const res = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7
      });

      const reply = res.choices?.[0]?.message?.content;
      if (!reply) return ctx.reply("❌ No response from AI");

      await ctx.reply(reply, { parse_mode: "Markdown" }).catch(() =>
        ctx.reply(reply)
      );
    } catch (err) {
      console.error("GPT ERROR:", err);
      ctx.reply("❌ AI error, try again later");
    }
  });

  /* ================= TEXT → IMAGE ================= */
  bot.command("text2image", async (ctx) => {
    const prompt = ctx.message.text.split(" ").slice(1).join(" ").trim();
    if (!prompt) return ctx.reply("❓ Usage: /text2image <prompt>");

    try {
      await ctx.replyWithChatAction("upload_photo");

      const img = await openai.images.generate({
        model: "gpt-image-1",
        prompt,
        size: "1024x1024"
      });

      const url = img.data?.[0]?.url;
      if (!url) return ctx.reply("❌ Image generation failed");

      await ctx.replyWithPhoto(url, {
        caption: "🖼 Generated by AI"
      });
    } catch (err) {
      console.error("IMAGE ERROR:", err);
      ctx.reply("❌ Image generation error");
    }
  });

  /* ================= TEXT → SPEECH ================= */
  bot.command("text2speech", async (ctx) => {
    const text = ctx.message.text.split(" ").slice(1).join(" ").trim();
    if (!text) return ctx.reply("❓ Usage: /text2speech <text>");

    try {
      await ctx.replyWithChatAction("record_audio");

      const speech = await openai.audio.speech.create({
        model: "gpt-4o-mini-tts",
        voice: "alloy",
        input: text
      });

      const buffer = Buffer.from(await speech.arrayBuffer());

      await ctx.replyWithAudio(
        { source: buffer },
        { title: "AI Voice", performer: "OpenAI" }
      );
    } catch (err) {
      console.error("TTS ERROR:", err);
      ctx.reply("❌ Text-to-speech failed");
    }
  });
}
    ctx.replyWithAudio({ source: Buffer.from(await audio.arrayBuffer()) })
  })
}
